# -*- mode: python -*- 
Import('env')
env=env.Clone()
env.Append(CPPPATH=['#sls/include'])
env.Append(LIBPATH=['#sls/libs'])

env.aProgram(target = 'lz4_sample', source = ['lz4_sample.cpp'], LIBS = ['lz4'])
